load("@com_google_protobuf//:protobuf.bzl", "cc_proto_library", "py_proto_library")

cc_proto_library(
  name = "example_proto",
  srcs = [
      "example.proto",
      "feature.proto",
  ],
  visibility = ["//visibility:public"],
)
